### ISSUE TITLE
support C/C++

### ISSUE THREAD

**Issue by adlternative** [sturdy-dev/semantic-code-search#14]
I love this fun and crazy project, can you make it support c/c++?

**Comment by adlternative** [comment]
Great!

**Comment by Hustcw** [comment]
I am curious about the direct support for C/C++ functions. I noticed that the commit at https://github.com/sturdy-dev/semantic-code-search/commit/b5ec8904e4c2c3b6f98a2687391e927abebbe32a introduced functionality for extracting C/C++ functions. However, I am a bit puzzled since, as far as I understand, the model is trained on the [code_search_net](https://huggingface.co/datasets/code_search_net) dataset, which, to my knowledge, doesn't include C/C++ datasets. Could you kindly provide some insight into how this integration was achieved?
